//! Minimal agent loop: ask Ollama, run any tools it requests, feed results
//! back, repeat until it stops asking for tools.

use crate::modules::ollama::service as ollama;
use crate::shared::state::AppState;
use serde_json::json;

const MAX_STEPS: usize = 5;

/// Where the reply text came from — provable, not guessable.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReplySource {
    /// Text generated by the LLM.
    Model,
    /// Verbatim output from a tool execution.
    Tool,
}

pub struct TurnResult {
    pub text: String,
    pub source: ReplySource,
}

pub async fn run_turn(state: &AppState, user_message: &str) -> Result<TurnResult, String> {
    let model = ollama::active_model().await?;

    let (ollama_tools, has_tools) = {
        let reg = state.mcp.read().await;
        (reg.ollama_tools(), !reg.is_empty())
    };

    let system = if has_tools {
        "Use the provided tools. Do not guess tool output.".to_string()
    } else {
        "Answer concisely.".to_string()
    };

    let mut messages = json!([
        { "role": "system", "content": system },
        { "role": "user", "content": user_message }
    ]);

    for step in 0..MAX_STEPS {
        let msg = ollama::chat_with_tools(&model, &messages, &ollama_tools).await?;

        if let Some(arr) = messages.as_array_mut() {
            arr.push(msg.clone());
        }

        let tool_calls = msg
            .get("tool_calls")
            .and_then(|v| v.as_array())
            .cloned()
            .unwrap_or_default();

        if tool_calls.is_empty() {
            let text = msg
                .get("content")
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string();
            return Ok(TurnResult {
                text,
                source: ReplySource::Model,
            });
        }

        let mut direct_reply: Option<String> = None;

        for call in tool_calls {
            let name = call
                .get("function")
                .and_then(|f| f.get("name"))
                .and_then(|v| v.as_str())
                .unwrap_or("")
                .to_string();
            let args = call
                .get("function")
                .and_then(|f| f.get("arguments"))
                .cloned()
                .unwrap_or(json!({}));

            state.emit_log("tool", &format!("[{step}] {name}")).await;

            let (result_text, is_direct) = match state.mcp.read().await.call_tool(&name, args).await
            {
                Ok((text, direct)) => {
                    state
                        .emit_log("tool", &format!("result ({} bytes)", text.len()))
                        .await;
                    (text, direct)
                }
                Err(e) => {
                    state.emit_log("tool", &format!("error: {e}")).await;
                    (format!("ERROR: {e}"), false)
                }
            };

            if is_direct {
                direct_reply = Some(result_text.clone());
            }

            if let Some(arr) = messages.as_array_mut() {
                arr.push(json!({
                    "role": "tool",
                    "name": name,
                    "content": result_text,
                }));
            }
        }

        if let Some(text) = direct_reply {
            return Ok(TurnResult {
                text,
                source: ReplySource::Tool,
            });
        }
    }

    Err(format!(
        "agent exceeded {MAX_STEPS} steps without finishing"
    ))
}
